variables:
  - &golang_image 'docker.io/golang:1.26'
  - &node_image 'docker.io/node:24-alpine'
  - &alpine_image 'docker.io/alpine:3.24'
  - path: &when_path
      - 'docs/**'
      - '.woodpecker/docs.yaml'
      - 'cli/**'
      - 'cmd/cli/**'
      - 'server/api/**'
  - path: &docker_path
      - 'web/**'
      - 'server/api/**'
      - '**/*.go'
      - 'go.*'
      - 'pipeline/schema/**'
      - 'docker/**'

when:
  - event: tag
    evaluate: 'not (CI_COMMIT_TAG contains "-lha-")'
  - event: pull_request
  - event: pull_request_closed
    path: *when_path
  - event: manual
    evaluate: 'TASK == "docs"'

steps:
  - name: install-dependencies
    image: *node_image
    directory: docs/
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile
    when:
      - path: *when_path
        event: [tag, pull_request]
      - event: manual

  - name: format-check
    image: *node_image
    directory: docs/
    commands:
      - corepack enable
      - pnpm format:check
    when:
      - path: *when_path
        event: pull_request

  - name: build-cli
    image: *golang_image
    commands:
      - make generate-docs
    when:
      - path: *when_path
        event: [tag, pull_request]
      - event: manual

  - name: build
    image: *node_image
    directory: docs/
    commands:
      - corepack enable
      - pnpm build
    when:
      - path: *when_path
        event: [tag, pull_request]
      - event: manual

  - name: deploy-preview
    image: docker.io/woodpeckerci/plugin-surge-preview:1.4.2
    settings:
      path: 'docs/build/'
      surge_token:
        from_secret: SURGE_TOKEN
      forge_repo_token:
        from_secret: GITHUB_TOKEN_SURGE
    failure: ignore
    when:
      - event: [pull_request, pull_request_closed]
        path: *when_path

  - name: deploy-prepare
    image: *alpine_image
    environment:
      BOT_PRIVATE_KEY:
        from_secret: BOT_PRIVATE_KEY
    commands:
      - apk add openssh-client git
      - mkdir -p $HOME/.ssh
      - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
      - echo "$BOT_PRIVATE_KEY" > $HOME/.ssh/id_rsa
      - chmod 0600 $HOME/.ssh/id_rsa
      - git clone --depth 1 --single-branch git@github.com:woodpecker-ci/woodpecker-ci.github.io.git ./docs_repo
    when:
      - event: [manual, tag]

  - name: version-release
    image: *alpine_image
    commands:
      - apk add jq
      - if [[ "${CI_COMMIT_TAG}" != *"rc"* ]] ; then jq '.latest = "${CI_COMMIT_TAG}"' ./docs_repo/version.json > ./docs_repo/version.json.tmp && mv ./docs_repo/version.json.tmp ./docs_repo/version.json ; fi
      - jq '.rc = "${CI_COMMIT_TAG}"' ./docs_repo/version.json > ./docs_repo/version.json.tmp
      - mv ./docs_repo/version.json.tmp ./docs_repo/version.json
    when:
      - event: tag

  - name: copy-files
    image: *alpine_image
    commands:
      - apk add rsync
      - rsync -r --exclude .git --exclude CNAME --exclude index.yaml --exclude README.md --exclude version.json --delete docs/build/ ./docs_repo
    when:
      - event: manual

  - name: deploy
    image: *alpine_image
    environment:
      BOT_PRIVATE_KEY:
        from_secret: BOT_PRIVATE_KEY
    commands:
      - apk add openssh-client rsync git
      - mkdir -p $HOME/.ssh
      - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
      - echo "$BOT_PRIVATE_KEY" > $HOME/.ssh/id_rsa
      - chmod 0600 $HOME/.ssh/id_rsa
      - git config --global user.email "woodpecker-bot@obermui.de"
      - git config --global user.name "woodpecker-bot"
      - cd ./docs_repo
      - git add .
      - test -n "$(git status --porcelain)" || exit 0
      - git commit -m "Deploy website - based on ${CI_COMMIT_SHA}"
      - git push
    when:
      - event: [manual, tag]
